### ISSUE TITLE
SplitLayer problem

### ISSUE THREAD

**Issue by andreistoian** [facebook/fb-caffe-exts#7]
Hi,

The memory optimizer works great for basic VGG but I have an error when sharing the results of the final layer between some new ones: a SplitLayer is created and an error is thrown saying "Layer does not allow in-place computation.". From the looks of it the optimizer tried to use the same blob for the input and the output blobs of the SplitLayer. From the code it is not clear how the SplitLayer case is handled. Do I need to add a special case in the optimizer to look for split Layers and adapt the LiveRanges accordingly?

Thanks,

**Comment by dkislyuk** [comment]
@andreistoian: I had the same issue, somewhat hackishly in my Caffe installation I had to remove the check altogether (from `src/caffe/layers/split_layer.cpp`)

```
-    CHECK_NE(top[i], bottom[0]) << this->type() << " Layer does not "
-        "allow in-place computation.";
```

to get the optimizer to work with custom VGG-derived architectures. I did not see any adverse affects from this in evaluation / performance.

**Comment by ajtulloch** [comment]
Sorry for the delay folks. If this is the problem I'm thinking of I fixed this internally a while ago, but didn't get around to pushing out the OSS version. Sorry about that.

I think https://github.com/facebook/fb-caffe-exts/commit/a8bba8660bdd2ddb6ab5409dd615139835f09a11 should fix the issue, LMK if it doesn't. Thanks.

**Comment by wangxianliang** [comment]
The bug still exists, for GoogLeNet. The error messages are as follows:
// Do not allow in-place computation in the SplitLayer.  Instead, share data
    // by reference in the forward pass, and keep separate diff allocations in
    // the backward pass.  (Technically, it should be possible to share the diff
    // blob of the first split output with the input, but this seems to cause
    // some strange effects in practice...)
    CHECK_NE(top[i], bottom[0]) << this->type() << " Layer does not "
        "allow in-place computation.";

**Comment by dkislyuk** [comment]
@wangxianliang does removing the check and re-compiling Caffe work?

**Comment by ajtulloch** [comment]
Yeah, move the CHECK to Backward_cpu pass.

``` diff
--- a/caffe/caffe-trunk/src/caffe/layers/split_layer.cpp
+++ b/caffe/caffe-trunk/src/caffe/layers/split_layer.cpp
@@ -16,8 +16,6 @@
     // the backward pass.  (Technically, it should be possible to share the diff
     // blob of the first split output with the input, but this seems to cause
     // some strange effects in practice...)
-    CHECK_NE(top[i], bottom[0]) << this->type() << " Layer does not "
-        "allow in-place computation.";
     top[i]->ReshapeLike(*bottom[0]);
     CHECK_EQ(count_, top[i]->count());
   }
@@ -36,13 +34,17 @@
       const vector<bool>& propagate_down, const vector<Blob<Dtype>*>& bottom) {
   if (!propagate_down[0]) { return; }
   if (top.size() == 1) {
+    CHECK_NE(top[0], bottom[0]) << this->type() << " Layer does not "
+        "allow in-place computation.";
     caffe_copy(count_, top[0]->cpu_diff(), bottom[0]->mutable_cpu_diff());
     return;
   }
   caffe_add(count_, top[0]->cpu_diff(), top[1]->cpu_diff(),
             bottom[0]->mutable_cpu_diff());
   // Add remaining top blob diffs.
   for (int i = 2; i < top.size(); ++i) {
+    CHECK_NE(top[i], bottom[0]) << this->type() << " Layer does not "
+        "allow in-place computation.";
     const Dtype* top_diff = top[i]->cpu_diff();
     Dtype* bottom_diff = bottom[0]->mutable_cpu_diff();
     caffe_axpy(count_, Dtype(1.), top_diff, bottom_diff);
```

**Comment by wangxianliang** [comment]
Removing the check does work, thanks a lot.
